#!/bin/bash

echo "Setting up AWS credentials..."
echo "Please run: aws configure"
echo ""
echo "You'll need:"
echo "1. AWS Access Key ID"
echo "2. AWS Secret Access Key"
echo "3. Default region (e.g., us-east-1)"
echo "4. Default output format (json)"
echo ""
echo "After configuration, run these commands to check your setup:"
echo ""
echo "# Test credentials"
echo "aws sts get-caller-identity"
echo ""
echo "# Check verified emails"
echo "aws ses list-verified-email-addresses --region us-east-1"
echo ""
echo "# Check SES quota"
echo "aws ses get-send-quota --region us-east-1"
echo ""
echo "# Run the email script"
echo "python aws_email_sender.py"
